# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1ea7e5e596d4fc8c52c0c88f3899db13485a86ea50a87e059f15c6c0e4c692fb3e637994c3ad7962dd431aa5bdf715f702e230eafd77fe40814deb1a3243860

test:
  secret_key_base: 594b905f57aadfd2910511e33305f4e31dc622809bcaa33e52b4dc13edabef8c61d32e7e2ebc5a2148270fe61c840d1105b88acd22fdbdde2711887999a795d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
